export {default as Navbar} from './navbar'
export {default as HomePage} from './HomePage'
export {default as About} from './About'
export {default as Portfolio} from './Portfolio'
export {default as Contact} from './Contact'